Pimcore\Bundle\StudioApiBundle\Dto\Task:
    attributes:
        id:
            groups: ['task:read', 'task:write']
        cid:
            groups: ['task:read', 'task:write']
        ctype:
            groups: ['task:read', 'task:write']
        date:
            groups: ['task:read', 'task:write']
        action:
            groups: ['task:read', 'task:write']
        version:
            groups: ['task:read', 'task:write']
        active:
            groups: ['task:read', 'task:write']
        userId:
            groups: ['task:read', 'task:write']