resources:
    Pimcore\Bundle\StudioApiBundle\Dto\Asset:
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters: [ Pimcore\Bundle\StudioApiBundle\Filter\AssetParentIdFilter ]
                paginationClientItemsPerPage: true
            ApiPlatform\Metadata\Get:
                normalizationContext:
                    groups: [ 'asset:read', 'asset:item:get', 'dependency:read', 'property:read']
            ApiPlatform\Metadata\Put:
            ApiPlatform\Metadata\Post:
            ApiPlatform\Metadata\Delete:
            ApiPlatform\Metadata\Patch:
        provider: Pimcore\Bundle\StudioApiBundle\State\AssetProvider
        normalizationContext:
            groups: ['asset:read', 'dependency:read', 'property:read']
        denormalizationContext:
            groups: ['asset:write']
        properties:
            id:
                identifier: true

properties:
    Pimcore\Bundle\StudioApiBundle\Dto\Asset:
        dependencies:
            genId: false