resources:
    Pimcore\Bundle\StudioApiBundle\Dto\Version:
        operations:
            ApiPlatform\Metadata\Get:
            ApiPlatform\Metadata\Put:
            ApiPlatform\Metadata\Post:
            ApiPlatform\Metadata\Delete:
            ApiPlatform\Metadata\Patch:
        provider: Pimcore\Bundle\StudioApiBundle\State\VersionProvider
        normalizationContext:
            groups: ['version:read']
        denormalizationContext:
            groups: ['version:write']
        properties:
            id:
                identifier: true