Pimcore\Bundle\StudioApiBundle\Dto\Version:
    attributes:
        id:
            groups: ['version:read', 'asset:item:get']
        cid:
            groups: ['version:read', 'asset:item:get']
        ctype:
            groups: ['version:read', 'asset:item:get']
        userId:
            groups: ['version:read', 'asset:item:get']
        user:
            groups: ['version:read', 'asset:item:get']
        note:
            groups: ['version:read', 'asset:item:get']
        date:
            groups: ['version:read', 'asset:item:get']
        data:
            groups: ['version:read']
        public:
            groups: ['version:read', 'asset:item:get']
        serialized:
            groups: ['version:read', 'asset:item:get']
        versionCount:
            groups: ['version:read', 'asset:item:get']
        binaryFileHash:
            groups: ['version:read', 'asset:item:get']
        binaryFileId:
            groups: ['version:read', 'asset:item:get']
        autosave:
            groups: ['version:read', 'asset:item:get']
        storageType:
            groups: ['version:read', 'asset:item:get']
